/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectriciansRouteImport } from './routes/electricians'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as PlumbersRouteImport } from './routes/plumbers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectriciansRoute = ElectriciansRouteImport.update({
  id: '/electricians',
  path: '/electricians',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbersRoute = PlumbersRouteImport.update({
  id: '/plumbers',
  path: '/plumbers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/emergency': typeof EmergencyRoute
  '/plumbers': typeof PlumbersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/emergency': typeof EmergencyRoute
  '/plumbers': typeof PlumbersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/emergency': typeof EmergencyRoute
  '/plumbers': typeof PlumbersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/electricians' | '/emergency' | '/plumbers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/electricians' | '/emergency' | '/plumbers'
  id: '__root__' | '/' | '/electricians' | '/emergency' | '/plumbers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElectriciansRoute: typeof ElectriciansRoute
  EmergencyRoute: typeof EmergencyRoute
  PlumbersRoute: typeof PlumbersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricians': {
      id: '/electricians'
      path: '/electricians'
      fullPath: '/electricians'
      preLoaderRoute: typeof ElectriciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbers': {
      id: '/plumbers'
      path: '/plumbers'
      fullPath: '/plumbers'
      preLoaderRoute: typeof PlumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElectriciansRoute: ElectriciansRoute,
  EmergencyRoute: EmergencyRoute,
  PlumbersRoute: PlumbersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
